name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mrkataei/mrkataei@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
